version: "3"
services:
  localstack:
    image: localstack/localstack:2.0
    networks:
      - hmpps
    container_name: localstack-test-hpe
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,sns
      - DEFAULT_REGION=eu-west-2
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"

# IMPORTANT: for Oracle, colima must be started and environment variables set: see README.md
  oracle-xe:
    image: gvenzl/oracle-xe:18-slim
    networks:
      - hmpps
    container_name: oracle-xe-hpe
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=test

networks:
  hmpps:
