server:
  shutdown: immediate
  port: 8083

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0

api:
  base:
    url:
      hmpps-auth: http://localhost:9090/auth

spring:
  flyway:
    enabled: true
    url: jdbc:oracle:thin:@//localhost:1521/XE
    user: "SYS AS SYSDBA"
    password: test
    baseline-on-migrate: true

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: HMPPS_EVENT_API
    password: test
    hikari:
      initialization-fail-timeout: -1

  exposed:
    show-sql: true

  jpa:
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
