# Per environment values which override defaults in hmpps-prisoner-events/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: prisoner-events-dev.prison.service.justice.gov.uk
    dso_enabled: false

  serviceAccountName: hmpps-prisoner-events

  scheduledDowntime:
    enabled: true
    startup: '17 6 * * 1-5' # Start at 6.17am UTC Monday-Friday
    shutdown: '49 21 * * 1-5' # Stop at 9.49pm UTC Monday-Friday

  allowlist:
    groups:
      - internal

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_HMPPS_AUTH: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    HMPPS_SQS_USE_WEB_TOKEN: true

cron:
  housekeeping_schedule: "*/10 7-20 * * 1-5"
