---
# Per environment values which override defaults in hmpps-prisoner-events/values.yaml

generic-service:
  poddisruptionbudget:
    enabled: true
    minAvailable: 3

  ingress:
    host: prisoner-events.aks-live-1.studio-hosting.service.justice.gov.uk
    annotations:
      # this magic line automatically generates a certificate for the ingress
      cert-manager.io/cluster-issuer: letsencrypt-production

  # Disabled for DSO AKS cluster
  allowlist: null

  env:
    API_BASE_URL_OAUTH: https://sign-in.hmpps.service.justice.gov.uk/auth
