---
# Per environment values which override defaults in hmpps-prisoner-events/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: prsnr-events-dev.aks-dev-1.studio-hosting.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    JMS_EVENTS_START: 2022-09-26T14:00:00
    JMS_EVENTS_END: 2023-10-03T00:00:00
