---
# Per environment values which override defaults in hmpps-prisoner-events/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: prsner-events-dev.aks-dev-1.studio-hosting.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
