---
# Per environment values which override defaults in hmpps-prisoner-events/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: prsnr-events-pp.aks-live-1.studio-hosting.service.justice.gov.uk

  scheduledDowntime:
    enabled: true
    startup: '16 6 * * 1-5' # Start at 6.16am UTC Monday-Friday
    shutdown: '48 21 * * 1-5' # Stop at 9.48pm UTC Monday-Friday

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
