---
# Per environment values which override defaults in hmpps-prisoner-events/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: prisoner-events-dev.prison.service.justice.gov.uk
    dso_enabled: false

  serviceAccountName: hmpps-prisoner-events

  scheduledDowntime:
    enabled: true
    startup: '17 6 * * 1-5' # Start at 6.17am UTC Monday-Friday
    shutdown: '49 21 * * 1-5' # Stop at 9.49pm UTC Monday-Friday

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    petty-france-wifi: "213.121.161.112/28"
    global-protect: "35.176.93.186/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live-1: "35.178.209.113/32"
    cloudplatform-live-2: "3.8.51.207/32"
    cloudplatform-live-3: "35.177.252.54/32"

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

cron:
  housekeeping_schedule: "*/10 7-20 * * 1-5"
