  CREATE TABLE "XTAG_LISTENER_TAB"
   ("Q_NAME" VARCHAR2(30 CHAR),
	"MSGID" RAW(16),
	"CORRID" VARCHAR2(128 CHAR),
	"PRIORITY" NUMBER,
	"STATE" NUMBER,
	"DELAY" TIMESTAMP (6),
	"EXPIRATION" NUMBER,
	"TIME_MANAGER_INFO" TIMESTAMP (6),
	"LOCAL_ORDER_NO" NUMBER,
	"CHAIN_NO" NUMBER,
	"CSCN" NUMBER,
	"DSCN" NUMBER,
	"ENQ_TIME" TIMESTAMP (6),
	"ENQ_UID" VARCHAR2(30 CHAR),
	"ENQ_TID" VARCHAR2(30 CHAR),
	"DEQ_TIME" TIMESTAMP (6),
	"DEQ_UID" VARCHAR2(30 CHAR),
	"DEQ_TID" VARCHAR2(30 CHAR),
	"RETRY_COUNT" NUMBER,
	"EXCEPTION_QSCHEMA" VARCHAR2(30 CHAR),
	"EXCEPTION_QUEUE" VARCHAR2(30 CHAR),
	"STEP_NO" NUMBER,
	"RECIPIENT_KEY" NUMBER,
	"DEQUEUE_MSGID" RAW(16),
	"SENDER_NAME" VARCHAR2(30 CHAR),
	"SENDER_ADDRESS" VARCHAR2(1024 CHAR),
	"SENDER_PROTOCOL" NUMBER,
	-- "USER_DATA" "SYS"."AQ$_JMS_MESSAGE" ,
	-- "USER_PROP" "SYS"."ANYDATA",
	CONSTRAINT "XTAG_LISTENER_TAB_PK" PRIMARY KEY ("MSGID")
   );

  CREATE INDEX "AQ$_XTAG_LISTENER_TAB_T" ON "XTAG_LISTENER_TAB" ("TIME_MANAGER_INFO") ;

  CREATE INDEX "AQ$_XTAG_LISTENER_TAB_I" ON "XTAG_LISTENER_TAB" ("Q_NAME", "STATE", "ENQ_TIME", "STEP_NO", "CHAIN_NO", "LOCAL_ORDER_NO")  ;

  CREATE UNIQUE INDEX "SYS_C0016182" ON "XTAG_LISTENER_TAB" ("MSGID") ;
