CREATE SEQUENCE OFFENDER_ID START WITH 1;
GRANT SELECT ON OFFENDER_ID TO HMPPS_EVENT_API;
CREATE PUBLIC SYNONYM OFFENDER_ID FOR SYS.OFFENDER_ID;

CREATE SEQUENCE OFFENDER_BOOK_ID START WITH 1;
GRANT SELECT ON OFFENDER_BOOK_ID TO HMPPS_EVENT_API;
CREATE PUBLIC SYNONYM OFFENDER_BOOK_ID FOR SYS.OFFENDER_BOOK_ID;

CREATE SEQUENCE PERSON_ID START WITH 1;
GRANT SELECT ON PERSON_ID TO HMPPS_EVENT_API;
CREATE PUBLIC SYNONYM PERSON_ID FOR SYS.PERSON_ID;

CREATE SEQUENCE OFFENDER_CONTACT_PERSON_ID START WITH 1;
GRANT SELECT ON OFFENDER_CONTACT_PERSON_ID TO HMPPS_EVENT_API;
CREATE PUBLIC SYNONYM OFFENDER_CONTACT_PERSON_ID FOR SYS.OFFENDER_CONTACT_PERSON_ID;

CREATE SEQUENCE OFFENDER_PERSON_RESTRICT_ID START WITH 1;
GRANT SELECT ON OFFENDER_PERSON_RESTRICT_ID TO HMPPS_EVENT_API;
CREATE PUBLIC SYNONYM OFFENDER_PERSON_RESTRICT_ID FOR SYS.OFFENDER_PERSON_RESTRICT_ID;



