---
generic-service:
  nameOverride: hmpps-prisoner-events
  productId: DPS060

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-prisoner-events
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    annotations:
      nginx.ingress.kubernetes.io/server-snippet: |
        server_tokens off;
        location /housekeeping {
          deny all;
          return 401;
        }
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: hmpps-prisoner-events-cert

  serviceAccountName: hmpps-prisoner-events

  allowlist:
    groups:
      - internal

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "oracle"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    JMS_CONNECTION_ORACLE_TRACELEVEL: 0
    JMS_CONNECTION_CONCURRENTCONSUMERS: 10
    JMS_CONNECTION_MAXCONCURRENTCONSUMERS: 20
    SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 21

  namespace_secrets:
    hmpps-prisoner-events-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    hmpps-prisoner-events:
      JDBC_URL: "JDBC_URL"
      DB_USERNAME: "DB_USERNAME"
      DB_PASSWORD: "DB_PASSWORD"
    offender-events-topic:
      HMPPS_SQS_TOPICS_PRISONEVENTTOPIC_ARN: "topic_arn"

generic-prometheus-alerts:
  targetApplication: hmpps-prisoner-events
  alertSeverity: syscon

cron:
  housekeeping_schedule: "*/10 * * * *"
