---
generic-service:
  nameOverride: hmpps-prisoner-events

  replicaCount: 4

  poddisruptionbudget:
    enabled: true
    minAvailable: 3

  image:
    repository: quay.io/hmpps/hmpps-prisoner-events
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    annotations:
      # this magic line automatically generates a certificate for the ingress
      cert-manager.io/cluster-issuer: letsencrypt-production
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: hmpps-prisoner-events-cert

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "oracle"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    HMPPS_ORACLE_DELAYMILLIS: 2000

  namespace_secrets:
    hmpps-prisoner-events:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      JDBC_URL: "JDBC_URL"
      DB_USERNAME: "DB_USERNAME"
      DB_PASSWORD: "DB_PASSWORD"
    offender-events-topic:
      HMPPS_SQS_TOPICS_PRISONEVENTTOPIC_ACCESS_KEY_ID: "access_key_id"
      HMPPS_SQS_TOPICS_PRISONEVENTTOPIC_SECRET_ACCESS_KEY: "secret_access_key"
      HMPPS_SQS_TOPICS_PRISONEVENTTOPIC_ARN: "topic_arn"

  # Disabled for DSO AKS cluster
  allowlist: null
