name: Run gradle checks with an oracle instance
on:
  workflow_call:
    inputs:
      java-version:
        type: string
        required: false
        default: '21'
      java-options:
        description: Any JAVA_OPTS that need to be set.  Not normally required when using github actions
        type: string
        default: ''
        required: false
      oracle-tag:
        type: string
        default: '18-slim'
        required: false
      oracle-password:
        type: string
        default: 'test'
        required: false
      gradle-command:
        description: The gradle command to execute
        type: string
        default: './gradlew check'
        required: false
      artifact-name:
        description: Unique name (across the pipeline) for the uploaded artifact
        type: string
        default: 'test-results'
        required: false
      build-artifact-name:
        description: Unique name (across the pipeline) for the uploaded build artifact
        type: string
        default: 'build-results'
        required: false
      build-dir:
        description: Path to find the artifacts e.g. necessary for multi-project gradle builds.
        type: string
        default: 'build'
        required: false
      upload-test-artifacts:
        description: Whether to upload test artifacts and generate test report
        type: boolean
        default: true
        required: false
      upload-build-artifacts:
        description: Whether to upload the uber jar and other required artifacts to build a docker image
        type: boolean
        default: false
        required: false
permissions:
  contents: read
jobs:
  gradle-oracle-verify:
    name: Verify the gradle app with oracle running
    runs-on: ubuntu-latest
    services:
      oracle:
        # Docker Hub Oracle image
        image: gvenzl/oracle-xe:${{ inputs.oracle-tag }}
        # Provide the configuration for oracle
        env:
          ORACLE_PASSWORD: ${{ inputs.oracle-password }}
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 1521:1521
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '${{ inputs.java-version }}'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run checks with gradle
        shell: bash
        run: |
          export JAVA_OPTS="${{ inputs.java-options }}"
          ${{ inputs.gradle-command }}
      - name: Upload the test artifacts
        if: ${{ inputs.upload-test-artifacts && !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: |
            ${{ inputs.build-dir }}/test-results
            ${{ inputs.build-dir }}/reports/tests
      - name: Upload the build artifacts
        if: ${{ inputs.upload-build-artifacts && !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.build-artifact-name }}
          path: |
            ${{ inputs.build-dir }}/libs
          retention-days: 1
      - name: publish test report
        if: ${{ inputs.upload-test-artifacts && !cancelled() && github.event.repository.visibility == 'public' }}
        uses: dorny/test-reporter@v2
        with:
          artifact: ${{ inputs.artifact-name }}
          name: Test Report
          path: 'test-results/**/*.xml'
          reporter: java-junit
          fail-on-empty: false
          fail-on-error: false
          list-suites: 'failed'
          list-tests: 'failed'
