
name: Run gradle checks with an oracle instance
on:
  workflow_call:
    inputs:
      java-version:
        type: string
        required: false
        default: '21'
      java-options:
        type: string
        default: ''
        required: false
      oracle-tag:
        type: string
        default: '18-slim'
        required: true
      oracle-password:
        type: string
        default: 'test'
        required: false
      gradle-command:
        type: string
        default: './gradlew check'
        required: false
permissions:
  contents: read
jobs:
  gradle-oracle-verify:
    runs-on: ubuntu-latest
    services:
      oracle:
        # Docker Hub Oracle image
        image: gvenzl/oracle-xe:${{ inputs.oracle-tag }}
        # Provide the configuration for oracle
        env:
          ORACLE_PASSWORD: ${{ inputs.oracle-password }}
        options: >-
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 1521:1521
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '${{ inputs.java-version }}'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run checks with gradle
        shell: bash
        run: |
          export JAVA_OPTS="${{ inputs.java-options }}"
          ${{ inputs.gradle-command }}
      - name: Upload the artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: upload test results
          path: |
            build/test-results
            build/reports/tests
